#//////////////////////////////////////////////////////////////////////////////////////
#//////////////////////////////////////////////////////////////////////////////////////

 
if(ENABLE_DEVICE)

# add choices when other backends are available
  set(SRCS
    detail/CUDA/cusparse_interface.cpp
  )

  add_library(sparse_lib ${SRCS})
  target_link_libraries(sparse_lib PUBLIC qmcio arch_lib nda_c) 

ENDIF()

