[mean_field.qe]
name = "mf"
prefix = "pwscf"
outdir = "../qe/OUT"
nbnd = 20

[interaction.cholesky]
name        = "eri"
mean_field  = "mf"
output      = "hamil.h5"
write_type  = "single"
tol         = 1e-4  # you may need to converge this value!
ecut        = 50
 
[hamiltonian]
mean_field  = "mf"
interaction = "eri"
output      = "hamil.h5"
 
