////////////////////////////////////////////////////////////////////////////////
// This file is distributed under the Apache License, Version 2.0 License.
// See LICENSE file in top directory for details.
//
// Copyright (c) 2021-2025 The Simons Foundation, Inc.
//
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// This file includes portions derived from work licensed under the
// University of Illinois/NCSA Open Source License. See the NOTICE file
// and LICENSES/NCSA.txt for details.
////////////////////////////////////////////////////////////////////////////////

// Regression tests for full2rdm, diagonal2rdm, and spinspinobs: compare the new
// (nda/mpi_context_t based) implementations against reference data produced by
// the old (pre-refactor) implementations on identical inputs. The reference
// file is generated by src/AFQMC/Estimators/tests/dump_rdm_reference.cpp in
// ~/src/SAFIRE_old, which writes three top-level case subgroups (closed,
// collinear, noncollinear) each with its own Metadata, Inputs, DiagTwoRDM, and
// SpinSpin. full2rdm output lives only under /collinear (full2rdm aborts on the
// other walker types).

#undef NDEBUG

#include "catch2/catch_test_macros.hpp"

#include "config.h"
#include "AFQMC/parameters.hpp"
#include "utilities/check.hpp"
#include "utilities/check_shape.hpp"
#include "test_common.hpp"
#include "utilities/h5_utils.hpp"

#include "nda/nda.hpp"
#include "nda/h5.hpp"
#include "h5/h5.hpp"

#include <cstdio>
#include <string>

#include "AFQMC/config.h"
#include "AFQMC/Estimators/Observables/full2rdm.hpp"
#include "AFQMC/Estimators/Observables/diagonal2rdm.hpp"
#include "AFQMC/Estimators/Observables/spinspin.hpp"
#include "AFQMC/Estimators/Observables/pair_correlators.hpp"

namespace sfqmc
{
using namespace afqmc;

namespace
{
struct ReferenceInputs
{
  int NMO, NAEA, NAEB, nwalk, nave;
  nda::array<ComplexType, 4> G;
  nda::vector<ComplexType> Xw;
  nda::vector<ComplexType> Wsum;
};

std::array<long, 4> g_shape(int nwalk, int NMO, WALKER_TYPES wt)
{
  // CLOSED:       (nwalk, 1, NMO,    NMO)
  // COLLINEAR:    (nwalk, 2, NMO,    NMO)
  // NONCOLLINEAR: (nwalk, 1, 2*NMO,  2*NMO)
  switch (wt)
  {
    case CLOSED:       return {nwalk, 1, NMO,     NMO};
    case COLLINEAR:    return {nwalk, 2, NMO,     NMO};
    case NONCOLLINEAR: return {nwalk, 1, 2 * NMO, 2 * NMO};
    default:
      utils::check(false, "unreachable: unknown walker type");
  }
  return {};
}

int expected_dm_size(int NMO, WALKER_TYPES wt)
{
  int dm = NMO * (2 * NMO - 1);
  if (wt == CLOSED) dm -= NMO * (NMO - 1) / 2;
  return dm;
}

ReferenceInputs read_reference_inputs(h5::group const& root,
                                      std::string const& case_group,
                                      WALKER_TYPES wt)
{
  ReferenceInputs r;
  h5::group gcase = root.open_group(case_group);

  h5::group meta = gcase.open_group("Metadata");
  h5::read(meta, "NMO", r.NMO);
  h5::read(meta, "NAEA", r.NAEA);
  h5::read(meta, "NAEB", r.NAEB);
  h5::read(meta, "nwalk", r.nwalk);
  h5::read(meta, "nave", r.nave);

  auto gshape = g_shape(r.nwalk, r.NMO, wt);
  r.G.resize(gshape);
  r.Xw.resize(r.nwalk);
  r.Wsum.resize(r.nave);

  h5::group inputs = gcase.open_group("Inputs");
  utils::h5_read(inputs, "G", r.G);
  utils::h5_read(inputs, "Xw", r.Xw);
  utils::h5_read(inputs, "Wsum", r.Wsum);
  return r;
}

std::string reference_file_path()
{
  return std::string(PROJECT_SOURCE_DIR_STR) + "/tests/unit_test_files/rdm_reference.h5";
}

template<MEMORY_SPACE MEM>
void observables_reference_diagonal2rdm(std::string const& case_group, WALKER_TYPES wt)
{
  auto& mpi = utils::make_unit_test_mpi_context();

  const std::string ref_file = reference_file_path();
  utils::check(utils::file_exists(ref_file), "Reference file not found: {}", ref_file);

  ReferenceInputs ref;
  nda::vector<ComplexType> ref_diag;
  ComplexType ref_denom;
  {
    h5::file file(ref_file, 'r');
    h5::group root(file);
    ref = read_reference_inputs(root, case_group, wt);

    ref_diag.resize(expected_dm_size(ref.NMO, wt));
    h5::group gcase = root.open_group(case_group);
    h5::group avg = gcase.open_group("DiagTwoRDM/Average_0");
    utils::h5_read(avg, "diag_two_rdm_000000000", ref_diag);
    h5::read(avg, "denominator_000000000", ref_denom);
  }

  diagonal2rdm<MEM> obs(mpi, DiagTwoRDMParameters{}, wt, ref.NMO, ref.nave);

  auto G_mem = memory::to_memory_space<MEM>(ref.G);
  obs.accumulate(0, G_mem, ref.G, ref.Xw, true);

  const std::string out_file =
      "test_diagonal2rdm_" + case_group + "_" + memory_space_to_string(MEM) + "_output.h5";
  {
    h5::file file(out_file, 'w');
    h5::group root(file);
    obs.print(0, std::addressof(root), ref.Wsum);
  }

  nda::vector<ComplexType> new_diag(ref_diag.size());
  ComplexType new_denom;
  {
    h5::file file(out_file, 'r');
    h5::group root(file);
    h5::group avg = root.open_group("DiagTwoRDM/Average_0");
    h5::read(avg, "diag_two_rdm_000000000", new_diag);
    h5::read(avg, "denominator_000000000", new_denom);
  }

  REQUIRE(new_diag.size() == ref_diag.size());
  CHECK_THAT(new_denom, utils::Approx(ref_denom));
  CHECK_THAT(new_diag, utils::Approx(ref_diag));

  if (mpi->comm.root())
    std::remove(out_file.c_str());
}

void observables_reference_spinspin(std::string const& case_group, WALKER_TYPES wt)
{
  auto& mpi = utils::make_unit_test_mpi_context();

  const std::string ref_file = reference_file_path();
  utils::check(utils::file_exists(ref_file), "Reference file not found: {}", ref_file);

  ReferenceInputs ref;
  nda::vector<ComplexType> ref_ss;
  ComplexType ref_denom;
  {
    h5::file file(ref_file, 'r');
    h5::group root(file);
    ref = read_reference_inputs(root, case_group, wt);

    ref_ss.resize(ref.NMO * (ref.NMO + 1));
    h5::group gcase = root.open_group(case_group);
    h5::group avg = gcase.open_group("SpinSpin/Average_0");
    utils::h5_read(avg, "spinspin_000000000", ref_ss);
    h5::read(avg, "denominator_000000000", ref_denom);
  }

  spinspinobs obs(mpi, SpinSpinCorrParameters{}, wt, ref.NMO, ref.nave);

  obs.accumulate(0, ref.G, nda::to_host(ref.G), ref.Xw, true);

  const std::string out_file = "test_spinspin_" + case_group + "_output.h5";
  {
    h5::file file(out_file, 'w');
    h5::group root(file);
    obs.print(0, std::addressof(root), ref.Wsum);
  }

  nda::vector<ComplexType> new_ss(ref_ss.size());
  ComplexType new_denom;
  {
    h5::file file(out_file, 'r');
    h5::group root(file);
    h5::group avg = root.open_group("SpinSpin/Average_0");
    h5::read(avg, "spinspin_000000000", new_ss);
    h5::read(avg, "denominator_000000000", new_denom);
  }

  REQUIRE(new_ss.size() == ref_ss.size());
  CHECK_THAT(new_denom, utils::Approx(ref_denom));
  CHECK_THAT(new_ss, utils::Approx(ref_ss));

  if (mpi->comm.root())
    std::remove(out_file.c_str());
}
template<MEMORY_SPACE MEM>
void observables_reference_full2rdm()
{
  auto& mpi = utils::make_unit_test_mpi_context();

  const std::string ref_file = reference_file_path();
  utils::check(utils::file_exists(ref_file), "Reference file not found: {}", ref_file);

  ReferenceInputs ref;
  nda::vector<ComplexType> ref_two_rdm;
  ComplexType ref_denom;
  {
    h5::file file(ref_file, 'r');
    h5::group root(file);
    ref = read_reference_inputs(root, "collinear", COLLINEAR);

    int dm_size = 3 * ref.NMO * ref.NMO * ref.NMO * ref.NMO;
    ref_two_rdm.resize(dm_size);
    h5::group gcase = root.open_group("collinear");
    h5::group avg = gcase.open_group("FullTwoRDM/Average_0");
    utils::h5_read(avg, "two_rdm_000000000", ref_two_rdm);
    h5::read(avg, "denominator_000000000", ref_denom);
  }

  full2rdm<MEM> obs(mpi, TwoRDMParameters{}, COLLINEAR, ref.NMO, ref.nave);

  auto G_mem = memory::to_memory_space<MEM>(ref.G);
  obs.accumulate(0, G_mem, ref.G, ref.Xw, true);

  const std::string out_file =
      "test_full2rdm_" + memory_space_to_string(MEM) + "_output.h5";
  {
    h5::file file(out_file, 'w');
    h5::group root(file);
    obs.print(0, std::addressof(root), ref.Wsum);
  }

  nda::vector<ComplexType> new_two_rdm(ref_two_rdm.size());
  ComplexType new_denom;
  {
    h5::file file(out_file, 'r');
    h5::group root(file);
    h5::group avg = root.open_group("FullTwoRDM/Average_0");
    h5::read(avg, "two_rdm_000000000", new_two_rdm);
    h5::read(avg, "denominator_000000000", new_denom);
  }

  REQUIRE(new_two_rdm.size() == ref_two_rdm.size());
  CHECK_THAT(new_denom, utils::Approx(ref_denom));
  CHECK_THAT(new_two_rdm, utils::Approx(ref_two_rdm));

  if (mpi->comm.root())
    std::remove(out_file.c_str());
}
// pair_correlator has no old-implementation reference data, so this checks the layout
// afqmctools.analysis.average.average_pair_correlation expects instead: the PairCorr group,
// its Metadata, and one NMO*NMO dataset per (alpha,beta) pair. The non-zero check guards
// against the observable silently measuring nothing.
void observables_reference_pair_correlator(std::string const& case_group, WALKER_TYPES wt)
{
  auto& mpi = utils::make_unit_test_mpi_context();

  const std::string ref_file = reference_file_path();
  utils::check(utils::file_exists(ref_file), "Reference file not found: {}", ref_file);

  ReferenceInputs ref;
  {
    h5::file file(ref_file, 'r');
    h5::group root(file);
    ref = read_reference_inputs(root, case_group, wt);
  }

  // identity and cyclic-shift pairings, i.e. the "s" and "+x" offsets of a 1d chain
  const std::vector<std::string> pair_type{"s", "+x"};
  const std::string map_file = "test_pair_correlator_" + case_group + "_map.h5";
  if (mpi->comm.root())
  {
    nda::array<int, 2> identity(ref.NMO, 1), shift(ref.NMO, 1);
    for (int i = 0; i < ref.NMO; i++)
    {
      identity(i, 0) = i;
      shift(i, 0)    = (i + 1) % ref.NMO;
    }
    h5::file file(map_file, 'w');
    // one level at a time: h5::group::has_key returns the raw htri_t from H5Lexists, which is
    // negative (i.e. true) when an intermediate component is missing, so create_group on a
    // nested path tries to unlink a link that does not exist and throws
    h5::group parent = h5::group(file).create_group("PairCorrelator");
    h5::group orbital_map = parent.create_group("orbital_map");
    h5::write(orbital_map, pair_type[0], identity);
    h5::write(orbital_map, pair_type[1], shift);
  }
  mpi->comm.barrier();

  PairCorrelatorParameters params;
  params.filename  = map_file;
  params.pair_type = pair_type;

  pair_correlator obs(mpi, params, wt, ref.NMO, ref.nave);

  obs.accumulate(0, ref.G, nda::to_host(ref.G), ref.Xw, true);

  const std::string out_file = "test_pair_correlator_" + case_group + "_output.h5";
  {
    h5::file file(out_file, 'w');
    h5::group root(file);
    obs.print(0, std::addressof(root), ref.Wsum);
  }

  const int ncorr   = int(pair_type.size());
  const int npairs  = ref.NMO * ref.NMO;

  nda::vector<ComplexType> new_pc(ncorr * ncorr * npairs);
  ComplexType new_denom;
  int new_ncorr;
  std::vector<std::string> new_names(ncorr);
  {
    h5::file file(out_file, 'r');
    h5::group root(file);
    h5::group parent = root.open_group("PairCorr");

    h5::group metadata = parent.open_group("Metadata");
    h5::read(metadata, "NCORRELATORS", new_ncorr);
    for (int i = 0; i < ncorr; i++)
    {
      // written as a char array so afqmctools can decode it with numpy's .tobytes()
      std::vector<char> name;
      h5::read(metadata, "CORRELATOR_NAME_" + std::to_string(i), name);
      new_names[i].assign(name.begin(), name.end());
    }

    h5::group avg = parent.open_group("Average_0");
    for (int alpha = 0; alpha < ncorr; alpha++)
    {
      for (int beta = 0; beta < ncorr; beta++)
      {
        std::string dset = std::format("P_{}_{}_ij_000000000", alpha, beta);
        auto info = h5::array_interface::get_dataset_info(avg, dset);
        utils::check_shape(info, dset, npairs);
        auto block = new_pc(nda::range((alpha * ncorr + beta) * npairs, (alpha * ncorr + beta + 1) * npairs));
        utils::h5_read(avg, dset, block);
      }
    }
    h5::read(avg, "denominator_000000000", new_denom);
  }

  CHECK(new_ncorr == ncorr);
  CHECK(new_names == pair_type);
  CHECK_THAT(new_denom, utils::Approx(ref.Wsum(0)));
  CHECK(nda::max_element(nda::abs(new_pc)) > 1e-12);

  if (mpi->comm.root())
  {
    std::remove(out_file.c_str());
    std::remove(map_file.c_str());
  }
}
} // namespace

TEST_CASE("observables_reference: full2rdm", "[observables_reference][full2rdm]")
{
  observables_reference_full2rdm<HOST_MEMORY>();
#if defined(ENABLE_DEVICE)
  observables_reference_full2rdm<DEVICE_MEMORY>();
#endif
}

TEST_CASE("observables_reference: diagonal2rdm closed",
          "[observables_reference][diagonal2rdm]")
{
  observables_reference_diagonal2rdm<HOST_MEMORY>("closed", CLOSED);
#if defined(ENABLE_DEVICE)
  observables_reference_diagonal2rdm<DEVICE_MEMORY>("closed", CLOSED);
#endif
}

TEST_CASE("observables_reference: diagonal2rdm collinear",
          "[observables_reference][diagonal2rdm]")
{
  observables_reference_diagonal2rdm<HOST_MEMORY>("collinear", COLLINEAR);
#if defined(ENABLE_DEVICE)
  observables_reference_diagonal2rdm<DEVICE_MEMORY>("collinear", COLLINEAR);
#endif
}

TEST_CASE("observables_reference: diagonal2rdm noncollinear",
          "[observables_reference][diagonal2rdm]")
{
  observables_reference_diagonal2rdm<HOST_MEMORY>("noncollinear", NONCOLLINEAR);
#if defined(ENABLE_DEVICE)
  observables_reference_diagonal2rdm<DEVICE_MEMORY>("noncollinear", NONCOLLINEAR);
#endif
}

TEST_CASE("observables_reference: spinspin closed",
          "[observables_reference][spinspin]")
{
  observables_reference_spinspin("closed", CLOSED);
}

TEST_CASE("observables_reference: spinspin collinear",
          "[observables_reference][spinspin]")
{
  observables_reference_spinspin("collinear", COLLINEAR);
}

TEST_CASE("observables_reference: spinspin noncollinear",
          "[observables_reference][spinspin]")
{
  observables_reference_spinspin("noncollinear", NONCOLLINEAR);
}

TEST_CASE("observables_reference: pair_correlator collinear",
          "[observables_reference][pair_correlator]")
{
  observables_reference_pair_correlator("collinear", COLLINEAR);
}

TEST_CASE("observables_reference: pair_correlator noncollinear",
          "[observables_reference][pair_correlator]")
{
  observables_reference_pair_correlator("noncollinear", NONCOLLINEAR);
}

} // namespace sfqmc
