[hamiltonian]
U = 2 # Hubbard U on site
#V = 0.0 # n_i n_j term, same as U1+U2
#U1 = 0.0 # n_i n_j different spin
#U2 = 0.0 # n_i n_j same spin
#J = 0.0 # J Hubbard Kanamori
# Note next nearest neighbor can be included via list
# V = [0.1, 0.2]
#### Hopping ####
# t = [1.0, -0.3] 

#### Spin Pinning #####
# h_afm_pin = 0.5 # Sz afm pinning
# h_afm_type = "staggered" # "staggered" | "fm"
# h_fm_pin = 0.5 # Sz fm pinning
# h_fm_type = "stagged" # "staggered" | "same"
#### Charge Pinning #####
# h_charge_pin = 0.5 # constant charge density pin

[lattice]
L1 = 4
L2 = 4
boundary1 = "PBC" # PBC or Open
boundary2 = "PBC" # PBC or Open
type = "square" # square, triangular, honeycomb, kagome
# twist=["1/16 Pi","1/16 Pi"] # can specify floats as well

[misc_params]
nelec = [8,8]
spin_symm = "collinear" # collinear | noncollinear
hdf5_outfile = "afqmc.h5"

[trial_wavefunction]
type = "hartree-fock" # "hartree-fock" | "free-electron"

[afqmc] # use this to set the input file afqmc.json
steps = 20000 # number of projection steps
timestep = 0.005 # Trotter step size
n_walkers_per_mpi_task = 100  # number of walkers PER MPI TASK - for a serial run, we want a few hundred.
seed = 0 # 0 sets seed based on time
#series = 10 # change output numbers
accumlate_interval = 2
population_control_interval = 2

#[afqmc.estimator]
#name = "back_propagation"
#path_restoration = true
#extra_path_restoration = true
#ortho = 2
#nsteps = 600
#naverages = 1
#equil = 2400
#
#[afqmc.estimator.onerdm]
#name = "one_rdm"

[trial_wavefunction.hartree_fock]
verbose = false
plot = false
output = "afqmc.h5"
noncollinear = false # for trial only, indpendent of AFQMC walkers
gpu = false
ansatz = "SD_ROT" # SD_ROT | SD_ROTC | DIAG | SLATERDET | SLATERDETC
opt_method = "lbfgs" # grad | lbfgs | basin
#seed = 0 # sets based on time by default
numSteps = 100
numTrials = 1
# dumpTrials = "afqmc_trials.npy" # additional data such as other higher energy states

# We can make an effective Hamiltonian for AutoHF that doesn't match AFQMC
#[trial_wavefunction.hamiltonian]
#U = 0.5
