////////////////////////////////////////////////////////////////////////////////
// This file is distributed under the Apache License, Version 2.0 License.
// See LICENSE file in top directory for details.
//
// Copyright (c) 2021-2025 The Simons Foundation, Inc.
//
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// This file includes portions derived from work licensed under the
// University of Illinois/NCSA Open Source License. See the NOTICE file
// and LICENSES/NCSA.txt for details.
////////////////////////////////////////////////////////////////////////////////

#include "catch_amalgamated.hpp"

#include "config.h"
#include "Utilities/AppAbort.hpp"

#include "hdf/hdf_archive.h"

#include <cstdio>
#include <map>
#include <set>
#include <string>
#include <vector>

#include "AFQMC/config.h"
#include "AFQMC/Utilities/AFQMCTimer.h"
#include "AFQMC/Utilities/Utils.hpp"
#include "AFQMC/Utilities/taskgroup.h"
#include "AFQMC/Estimators/Observables/full1rdm.hpp"
#include "Memory/buffer_managers.h"

namespace sfqmc
{
using namespace afqmc;

namespace
{

struct ReferenceMetadata
{
	int NMO;
	int NAEA;
	int NAEB;
	std::vector<WALKER_TYPES> walker_types;
};

int spin_blocks(WALKER_TYPES wt)
{
	return (wt == COLLINEAR) ? 2 : 1;
}

int matrix_dim(WALKER_TYPES wt, int NMO)
{
	return (wt == NONCOLLINEAR) ? 2 * NMO : NMO;
}

std::string walker_type_tag(WALKER_TYPES wt)
{
	switch (wt)
	{
	case CLOSED:
		return "closed";
	case COLLINEAR:
		return "collinear";
	case NONCOLLINEAR:
		return "noncollinear";
	case FULLYPOLARIZED:
		return "fullypolarized";
	default:
		return "undefined";
	}
}

bool skip_observable_for_walker_type(const std::string& observable_name, WALKER_TYPES wt)
{
	// Scaffolding for future selective skips per observable.
	static const std::map<std::string, std::set<WALKER_TYPES>> skip_map = {
			{"one_rdm", {}},
			{"two_rdm", {}},
			{"diag2rdm", {}},
			{"spinspin", {}},
			{"pair_correlators", {}}};

	auto it = skip_map.find(observable_name);
	if (it == skip_map.end())
		return false;
	return (it->second.find(wt) != it->second.end());
}

ReferenceMetadata read_reference_metadata(const std::string& ref_file)
{
	hdf_archive ref;
	if (!ref.open(ref_file, H5F_ACC_RDONLY))
		APP_ABORT("Unable to open reference file: {}", ref_file);

	ReferenceMetadata m;
	ref.read(m.NMO, "Metadata/NMO");
	ref.read(m.NAEA, "Metadata/NAEA");
	ref.read(m.NAEB, "Metadata/NAEB");

	// Reference file contains references for all walker types (generated by Python utility)
	m.walker_types = {CLOSED, COLLINEAR, NONCOLLINEAR, FULLYPOLARIZED};

	ref.close();
	return m;
}

void check_close(const ComplexType& a, const ComplexType& b)
{
	REQUIRE(a.real() == Approx(b.real()));
	REQUIRE(a.imag() == Approx(b.imag()));
}

} // namespace

TEST_CASE("observables_scaffold_onerdm", "[estimators][observables]")
{
	auto world = boost::mpi3::environment::get_world_instance();
	auto node  = world.split_shared(world.rank());
	setup_loggers(world.root(), 2, 0);

#if defined(ENABLE_CUDA) || defined(ENABLE_HIP)
	arch::INIT(node);
#endif

	setup_AFQMC_timer();
	setup_memory_managers(node, 10uL * 1024uL * 1024uL);

	// Reference file path (generated by generate_observable_references.py)
	const std::string ref_file = "test_observables_reference.h5";
	
	// TaskGroup used to construct observables directly.
	afqmc::GlobalTaskGroup gTG(world);
	auto TG = TaskGroup_(gTG, std::string("ObsTG"), 1, gTG.getTotalCores());

	// 1) Open the static reference HDF5 file
	if (!file_exists(ref_file))
		APP_ABORT("Reference file not found: {}. Generate with: python generate_observable_references.py", ref_file);

	// 2) Read metadata
	auto metadata = read_reference_metadata(ref_file);
	const int NMO   = metadata.NMO;
	const int NAEA  = metadata.NAEA;
	const int NAEB  = metadata.NAEB;
	const int nwalk = 1;

	// 3) Test each walker type from reference metadata
	for (auto wt : metadata.walker_types)
	{
		// 4) Loop observables (for now: one_rdm only)
		for (const std::string& observable_name : std::vector<std::string>{"one_rdm"})
		{
			if (skip_observable_for_walker_type(observable_name, wt))
				continue;

			if (observable_name == "one_rdm")
			{
				AFQMCInfo info{"obs_info", NMO, NAEA, NAEB};
				ptree obs_pt;

				// 5) Construct observable for this walker type
				full1rdm obs(TG, info, obs_pt, wt, 1, 1);

				// 6) Read G from reference file (same G used to compute reference observable)
				std::vector<ComplexType> G_ref_vec;
				hdf_archive G_reader;
				if (!G_reader.open(ref_file, H5F_ACC_RDONLY))
					APP_ABORT("Unable to open reference file for G: {}", ref_file);
				const std::string ref_prefix_G = "Reference/OneRDM/Walker_" + walker_type_tag(wt) + "/";
				G_reader.read(G_ref_vec, ref_prefix_G + "G_000000000");
				G_reader.close();

				// Reshape G_ref_vec into 4D array [nwalk, nspin, nM, nM]
				int nspin = spin_blocks(wt);
				int nM = matrix_dim(wt, NMO);
				boost::multi::array<ComplexType, 4> G({nwalk, nspin, nM, nM});
				std::copy(G_ref_vec.begin(), G_ref_vec.end(), G.origin());
				
				boost::multi::array<ComplexType, 1> Xw({nwalk});
				Xw[0] = ComplexType(1.0, 0.0);

				// 7) accumulate(..., G, ...)
				obs.accumulate(0, G, G, Xw, true);

				boost::multi::array<ComplexType, 1> Wsum({1});
				Wsum[0] = ComplexType(1.0, 0.0);

				// 8) print() -> temporary HDF5 output
				const std::string out_file = "test_observables_output_" + walker_type_tag(wt) + ".h5";
				hdf_archive out;
				if (!out.create(out_file))
					APP_ABORT("Unable to create output file: {}", out_file);
				out.open(out_file);
				obs.print(0, out, Wsum);
				out.close();

				// 9) Read test output
				std::vector<ComplexType> test_one_rdm;
				ComplexType test_denom;
				hdf_archive test_reader;
				if (!test_reader.open(out_file, H5F_ACC_RDONLY))
					APP_ABORT("Unable to open output file: {}", out_file);
				test_reader.readEntry(test_one_rdm, "FullOneRDM/Average_0/one_rdm_000000000");
				test_reader.readEntry(test_denom, "FullOneRDM/Average_0/denominator_000000000");
				test_reader.close();

				// 10) Read reference result for this observable/walker_type
				std::vector<ComplexType> ref_one_rdm;
				std::vector<double> ref_denom_vec;
				hdf_archive ref_reader;
				if (!ref_reader.open(ref_file, H5F_ACC_RDONLY))
					APP_ABORT("Unable to open reference file: {}", ref_file);
				const std::string ref_prefix =
						"Reference/OneRDM/Walker_" + walker_type_tag(wt) + std::string("/");
				
				// Use read() instead of readEntry() for better error messages
				try {
					ref_reader.read(ref_one_rdm, ref_prefix + "one_rdm_000000000");
					ref_reader.read(ref_denom_vec, ref_prefix + "denominator_000000000");
				} catch (const std::exception& e) {
					APP_ABORT("Failed to read from reference file: {}", e.what());
				}
				ref_reader.close();

				// 11) Compare: test output against reference
				REQUIRE(ref_denom_vec.size() == 2);
				ComplexType ref_denom(ref_denom_vec[0], ref_denom_vec[1]);
                check_close(test_denom, ref_denom);
				
                std::cout << "Testing one_rdm for walker type: " << walker_type_tag(wt) << std::endl;
				REQUIRE(test_one_rdm.size() == ref_one_rdm.size());
				for (int i = 0; i < test_one_rdm.size(); ++i)
					check_close(test_one_rdm[i], ref_one_rdm[i]);
			}
		}
	}

	world.barrier();
	if (world.root())
	{
		std::remove("test_observables_output_closed.h5");
		std::remove("test_observables_output_collinear.h5");
		std::remove("test_observables_output_noncollinear.h5");
		std::remove("test_observables_output_fullypolarized.h5");
	}

	release_memory_managers();
}

} // namespace sfqmc
