////////////////////////////////////////////////////////////////////////////////
// This file is distributed under the Apache License, Version 2.0 License.
// See LICENSE file in top directory for details.
//
// Copyright (c) 2021-2025 The Simons Foundation, Inc.
//
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// This file includes portions derived from work licensed under the
// University of Illinois/NCSA Open Source License. See the NOTICE file
// and LICENSES/NCSA.txt for details.
////////////////////////////////////////////////////////////////////////////////

// Regression tests for full2rdm, diagonal2rdm, and spinspinobs: compare the new
// (nda/mpi_context_t based) implementations against reference data produced by
// the old (pre-refactor) implementations on identical inputs. The reference
// file is generated by src/AFQMC/Estimators/tests/dump_rdm_reference.cpp in
// ~/src/SAFIRE_old, which writes three top-level case subgroups (closed,
// collinear, noncollinear) each with its own Metadata, Inputs, DiagTwoRDM, and
// SpinSpin. full2rdm output lives only under /collinear (full2rdm aborts on the
// other walker types).

#undef NDEBUG

#include "catch2/catch.hpp"

#include "config.h"
#include "IO/ptree/ptree_utilities.hpp"
#include "utilities/check.hpp"
#include "utilities/test_common.hpp"
#include "utilities/h5_utils.hpp"

#include "nda/nda.hpp"
#include "nda/h5.hpp"
#include "h5/h5.hpp"

#include <cstdio>
#include <string>

#include "AFQMC/config.h"
#include "AFQMC/Estimators/Observables/full2rdm.hpp"
#include "AFQMC/Estimators/Observables/diagonal2rdm.hpp"
#include "AFQMC/Estimators/Observables/spinspin.hpp"

namespace sfqmc
{
using namespace afqmc;

namespace
{
struct ReferenceInputs
{
  int NMO, NAEA, NAEB, nwalk, nave;
  nda::array<ComplexType, 4> G;
  nda::vector<ComplexType> Xw;
  nda::vector<ComplexType> Wsum;
};

std::array<long, 4> g_shape(int nwalk, int NMO, WALKER_TYPES wt)
{
  // CLOSED:       (nwalk, 1, NMO,    NMO)
  // COLLINEAR:    (nwalk, 2, NMO,    NMO)
  // NONCOLLINEAR: (nwalk, 1, 2*NMO,  2*NMO)
  switch (wt)
  {
    case CLOSED:       return {nwalk, 1, NMO,     NMO};
    case COLLINEAR:    return {nwalk, 2, NMO,     NMO};
    case NONCOLLINEAR: return {nwalk, 1, 2 * NMO, 2 * NMO};
  }
  utils::check(false, "unreachable: unknown walker type");
  return {};
}

int expected_dm_size(int NMO, WALKER_TYPES wt)
{
  int dm = NMO * (2 * NMO - 1);
  if (wt == CLOSED) dm -= NMO * (NMO - 1) / 2;
  return dm;
}

ReferenceInputs read_reference_inputs(h5::group const& root,
                                      std::string const& case_group,
                                      WALKER_TYPES wt)
{
  ReferenceInputs r;
  h5::group gcase = root.open_group(case_group);

  h5::group meta = gcase.open_group("Metadata");
  h5::read(meta, "NMO", r.NMO);
  h5::read(meta, "NAEA", r.NAEA);
  h5::read(meta, "NAEB", r.NAEB);
  h5::read(meta, "nwalk", r.nwalk);
  h5::read(meta, "nave", r.nave);

  auto gshape = g_shape(r.nwalk, r.NMO, wt);
  r.G.resize(gshape);
  r.Xw.resize(r.nwalk);
  r.Wsum.resize(r.nave);

  h5::group inputs = gcase.open_group("Inputs");
  utils::h5_read(inputs, "G", r.G);
  utils::h5_read(inputs, "Xw", r.Xw);
  utils::h5_read(inputs, "Wsum", r.Wsum);
  return r;
}

std::string reference_file_path()
{
  return std::string(PROJECT_SOURCE_DIR_STR) + "/tests/unit_test_files/rdm_reference.h5";
}

template<MEMORY_SPACE MEM>
void compare_diagonal2rdm_case(std::string const& case_group, WALKER_TYPES wt)
{
  auto& mpi = utils::make_unit_test_mpi_context();

  const std::string ref_file = reference_file_path();
  utils::check(utils::file_exists(ref_file), "Reference file not found: {}", ref_file);

  ReferenceInputs ref;
  nda::vector<ComplexType> ref_diag;
  ComplexType ref_denom;
  {
    h5::file file(ref_file, 'r');
    h5::group root(file);
    ref = read_reference_inputs(root, case_group, wt);

    ref_diag.resize(expected_dm_size(ref.NMO, wt));
    h5::group gcase = root.open_group(case_group);
    h5::group avg = gcase.open_group("DiagTwoRDM/Average_0");
    utils::h5_read(avg, "diag_two_rdm_000000000", ref_diag);
    h5::read(avg, "denominator_000000000", ref_denom);
  }

  AFQMCInfo info{"diagonal2rdm_test_info", ref.NMO, ref.NAEA, ref.NAEB};
  ptree obs_pt;
  diagonal2rdm<MEM> obs(mpi, info, obs_pt, wt, ref.nave);

  auto G_mem = memory::to_memory_space<MEM>(ref.G);
  obs.accumulate(0, G_mem, ref.G, ref.Xw, true);

  const std::string out_file =
      "test_diagonal2rdm_" + case_group + "_" + memory_space_to_string(MEM) + "_output.h5";
  {
    h5::file file(out_file, 'w');
    h5::group root(file);
    obs.print(0, std::addressof(root), ref.Wsum);
  }

  nda::vector<ComplexType> new_diag(ref_diag.size());
  ComplexType new_denom;
  {
    h5::file file(out_file, 'r');
    h5::group root(file);
    h5::group avg = root.open_group("DiagTwoRDM/Average_0");
    h5::read(avg, "diag_two_rdm_000000000", new_diag);
    h5::read(avg, "denominator_000000000", new_denom);
  }

  REQUIRE(new_diag.size() == ref_diag.size());
  utils::VALUE_EQUAL(new_denom, ref_denom);
  utils::ARRAY_EQUAL(new_diag, ref_diag);

  if (mpi->comm.root())
    std::remove(out_file.c_str());
}

void compare_spinspin_case(std::string const& case_group, WALKER_TYPES wt)
{
  auto& mpi = utils::make_unit_test_mpi_context();

  const std::string ref_file = reference_file_path();
  utils::check(utils::file_exists(ref_file), "Reference file not found: {}", ref_file);

  ReferenceInputs ref;
  nda::vector<ComplexType> ref_ss;
  ComplexType ref_denom;
  {
    h5::file file(ref_file, 'r');
    h5::group root(file);
    ref = read_reference_inputs(root, case_group, wt);

    ref_ss.resize(ref.NMO * (ref.NMO + 1));
    h5::group gcase = root.open_group(case_group);
    h5::group avg = gcase.open_group("SpinSpin/Average_0");
    utils::h5_read(avg, "spinspin_000000000", ref_ss);
    h5::read(avg, "denominator_000000000", ref_denom);
  }

  AFQMCInfo info{"spinspin_test_info", ref.NMO, ref.NAEA, ref.NAEB};
  ptree obs_pt;
  spinspinobs obs(mpi, info, obs_pt, wt, ref.nave);

  obs.accumulate(0, ref.G, nda::to_host(ref.G), ref.Xw, true);

  const std::string out_file = "test_spinspin_" + case_group + "_output.h5";
  {
    h5::file file(out_file, 'w');
    h5::group root(file);
    obs.print(0, std::addressof(root), ref.Wsum);
  }

  nda::vector<ComplexType> new_ss(ref_ss.size());
  ComplexType new_denom;
  {
    h5::file file(out_file, 'r');
    h5::group root(file);
    h5::group avg = root.open_group("SpinSpin/Average_0");
    h5::read(avg, "spinspin_000000000", new_ss);
    h5::read(avg, "denominator_000000000", new_denom);
  }

  REQUIRE(new_ss.size() == ref_ss.size());
  utils::VALUE_EQUAL(new_denom, ref_denom);
  utils::ARRAY_EQUAL(new_ss, ref_ss);

  if (mpi->comm.root())
    std::remove(out_file.c_str());
}
template<MEMORY_SPACE MEM>
void compare_full2rdm_case()
{
  auto& mpi = utils::make_unit_test_mpi_context();

  const std::string ref_file = reference_file_path();
  utils::check(utils::file_exists(ref_file), "Reference file not found: {}", ref_file);

  ReferenceInputs ref;
  nda::vector<ComplexType> ref_two_rdm;
  ComplexType ref_denom;
  {
    h5::file file(ref_file, 'r');
    h5::group root(file);
    ref = read_reference_inputs(root, "collinear", COLLINEAR);

    int dm_size = 3 * ref.NMO * ref.NMO * ref.NMO * ref.NMO;
    ref_two_rdm.resize(dm_size);
    h5::group gcase = root.open_group("collinear");
    h5::group avg = gcase.open_group("FullTwoRDM/Average_0");
    utils::h5_read(avg, "two_rdm_000000000", ref_two_rdm);
    h5::read(avg, "denominator_000000000", ref_denom);
  }

  AFQMCInfo info{"full2rdm_test_info", ref.NMO, ref.NAEA, ref.NAEB};
  ptree obs_pt;
  full2rdm<MEM> obs(mpi, info, obs_pt, COLLINEAR, ref.nave);

  auto G_mem = memory::to_memory_space<MEM>(ref.G);
  obs.accumulate(0, G_mem, ref.G, ref.Xw, true);

  const std::string out_file =
      "test_full2rdm_" + memory_space_to_string(MEM) + "_output.h5";
  {
    h5::file file(out_file, 'w');
    h5::group root(file);
    obs.print(0, std::addressof(root), ref.Wsum);
  }

  nda::vector<ComplexType> new_two_rdm(ref_two_rdm.size());
  ComplexType new_denom;
  {
    h5::file file(out_file, 'r');
    h5::group root(file);
    h5::group avg = root.open_group("FullTwoRDM/Average_0");
    h5::read(avg, "two_rdm_000000000", new_two_rdm);
    h5::read(avg, "denominator_000000000", new_denom);
  }

  REQUIRE(new_two_rdm.size() == ref_two_rdm.size());
  utils::VALUE_EQUAL(new_denom, ref_denom);
  utils::ARRAY_EQUAL(new_two_rdm, ref_two_rdm);

  if (mpi->comm.root())
    std::remove(out_file.c_str());
}
} // namespace

TEST_CASE("full2rdm_vs_old_reference", "[estimators][observables][full2rdm]")
{
  compare_full2rdm_case<HOST_MEMORY>();
#if defined(ENABLE_DEVICE)
  compare_full2rdm_case<DEVICE_MEMORY>();
#endif
}

TEST_CASE("diagonal2rdm_vs_old_reference_closed",
          "[estimators][observables][diagonal2rdm]")
{
  compare_diagonal2rdm_case<HOST_MEMORY>("closed", CLOSED);
#if defined(ENABLE_DEVICE)
  compare_diagonal2rdm_case<DEVICE_MEMORY>("closed", CLOSED);
#endif
}

TEST_CASE("diagonal2rdm_vs_old_reference_collinear",
          "[estimators][observables][diagonal2rdm]")
{
  compare_diagonal2rdm_case<HOST_MEMORY>("collinear", COLLINEAR);
#if defined(ENABLE_DEVICE)
  compare_diagonal2rdm_case<DEVICE_MEMORY>("collinear", COLLINEAR);
#endif
}

TEST_CASE("diagonal2rdm_vs_old_reference_noncollinear",
          "[estimators][observables][diagonal2rdm]")
{
  compare_diagonal2rdm_case<HOST_MEMORY>("noncollinear", NONCOLLINEAR);
#if defined(ENABLE_DEVICE)
  compare_diagonal2rdm_case<DEVICE_MEMORY>("noncollinear", NONCOLLINEAR);
#endif
}

TEST_CASE("spinspin_vs_old_reference_closed",
          "[estimators][observables][spinspin]")
{
  compare_spinspin_case("closed", CLOSED);
}

TEST_CASE("spinspin_vs_old_reference_collinear",
          "[estimators][observables][spinspin]")
{
  compare_spinspin_case("collinear", COLLINEAR);
}

TEST_CASE("spinspin_vs_old_reference_noncollinear",
          "[estimators][observables][spinspin]")
{
  compare_spinspin_case("noncollinear", NONCOLLINEAR);
}

} // namespace sfqmc
