////////////////////////////////////////////////////////////////////////////////
// This file is distributed under the Apache License, Version 2.0 License.
// See LICENSE file in top directory for details.
//
// Copyright (c) 2021-2025 The Simons Foundation, Inc.
//
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// This file includes portions derived from work licensed under the
// University of Illinois/NCSA Open Source License. See the NOTICE file
// and LICENSES/NCSA.txt for details.
////////////////////////////////////////////////////////////////////////////////

// Regression test for full2rdm: compares the new (nda/mpi_context_t based)
// implementation against reference data produced by the old (pre-refactor)
// implementation on identical inputs. The reference file is generated by
// src/AFQMC/Estimators/tests/dump_full2rdm_reference.cpp in ~/src/SAFIRE_old.

#undef NDEBUG

#include "catch2/catch.hpp"

#include "config.h"
#include "IO/ptree/ptree_utilities.hpp"
#include "utilities/check.hpp"
#include "utilities/test_common.hpp"
#include "utilities/h5_utils.hpp"

#include "nda/nda.hpp"
#include "nda/h5.hpp"
#include "h5/h5.hpp"

#include <cstdio>
#include <string>

#include "AFQMC/config.h"
#include "AFQMC/Estimators/Observables/full2rdm.hpp"

namespace sfqmc
{
using namespace afqmc;

TEST_CASE("full2rdm_vs_old_reference", "[estimators][observables][full2rdm]")
{
  auto& mpi = utils::make_unit_test_mpi_context();

  const std::string ref_file =
      std::string(PROJECT_SOURCE_DIR_STR) + "/tests/unit_test_files/full2rdm_reference.h5";
  utils::check(utils::file_exists(ref_file), "Reference file not found: {}", ref_file);

  // Read metadata and inputs from the reference file.
  int NMO, NAEA, NAEB, nwalk, nave;
  nda::array<ComplexType, 4> G;
  nda::vector<ComplexType> Xw;
  nda::vector<ComplexType> Wsum;
  nda::vector<ComplexType> ref_two_rdm;
  ComplexType ref_denom;
  {
    h5::file file(ref_file, 'r');
    h5::group root(file);

    h5::group meta = root.open_group("Metadata");
    h5::read(meta, "NMO", NMO);
    h5::read(meta, "NAEA", NAEA);
    h5::read(meta, "NAEB", NAEB);
    h5::read(meta, "nwalk", nwalk);
    h5::read(meta, "nave", nave);

    h5::group inputs = root.open_group("Inputs");
    G.resize(nwalk, 2, NMO, NMO);
    Xw.resize(nwalk);
    Wsum.resize(nave);
    utils::h5_read(inputs, "G", G);
    utils::h5_read(inputs, "Xw", Xw);
    utils::h5_read(inputs, "Wsum", Wsum);

    int dm_size = 3 * NMO * NMO * NMO * NMO;
    ref_two_rdm.resize(dm_size);
    h5::group avg = root.open_group("FullTwoRDM/Average_0");
    utils::h5_read(avg, "two_rdm_000000000", ref_two_rdm);
    h5::read(avg, "denominator_000000000", ref_denom);
  }

  // Construct and run the new implementation on the same inputs.
  AFQMCInfo info{"full2rdm_test_info", NMO, NAEA, NAEB};
  ptree obs_pt;
  full2rdm obs(mpi, info, obs_pt, COLLINEAR, nave, /*block_size=*/1);

  obs.accumulate(0, G, Xw, true);

  const std::string out_file = "test_full2rdm_output.h5";
  {
    h5::file file(out_file, 'w');
    h5::group root(file);
    // full2rdm::print uses open_group, so the target groups must exist.
    for (int i = 0; i < nave; ++i)
      root.create_group("FullTwoRDM").create_group("Average_" + std::to_string(i));
    obs.print(0, std::addressof(root), Wsum);
  }

  // Read the new implementation's output and compare to reference.
  nda::vector<ComplexType> new_two_rdm(ref_two_rdm.size());
  ComplexType new_denom;
  {
    h5::file file(out_file, 'r');
    h5::group root(file);
    h5::group avg = root.open_group("FullTwoRDM/Average_0");
    h5::read(avg, "two_rdm_000000000", new_two_rdm);
    h5::read(avg, "denominator_000000000", new_denom);
  }

  REQUIRE(new_two_rdm.size() == ref_two_rdm.size());
  utils::VALUE_EQUAL(new_denom, ref_denom);
  utils::ARRAY_EQUAL(new_two_rdm(nda::range(2*NMO*NMO*NMO*NMO,3*NMO*NMO*NMO*NMO)), ref_two_rdm(nda::range(2*NMO*NMO*NMO*NMO,3*NMO*NMO*NMO*NMO)));

  if (mpi->comm.root())
    std::remove(out_file.c_str());

  
}

} // namespace sfqmc
