FROM naive_afqmc_ubuntu

WORKDIR /var/app/
ENV DEBIAN_FRONTEND noninteractive

SHELL ["/bin/bash", "-c"]

# checkout source from private repo via ssh
RUN mkdir -p -m 0700 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN --mount=type=ssh cd /var/app/afqmc \
    && git fetch \
    && git checkout pre_beta

# Build Python layer
RUN source /var/app/venv/bin/activate \
   && pip install /var/app/afqmc/utils[AUTOHF,PYSCF,TESTING] \
   && cd /var/app/afqmc/utils \
   && pytest -vvv -rP
