FROM nvidia/cuda:12.4.1-devel-ubuntu22.04

WORKDIR /var/app/
ENV DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-c"]

# install dependencies
RUN apt-get update && apt-get install -y openssh-client git \
   gcc \
   g++ \
   cmake \
   openmpi-bin \
   openmpi-common \
   libopenmpi-dev \
   libopenblas-dev \
   libhdf5-openmpi-dev \
   python3 \
   python3-pip \
   libboost-dev \
   python3-mpi4py \
   python3-h5py-mpi \
   python3-venv

# checkout source from private repo via ssh
RUN mkdir -p -m 0700 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN --mount=type=ssh \
   git clone --progress --verbose git@github.com:SFQMC/SAFIRE.git afqmc \
   && cd afqmc \
   && git submodule init \
   && git submodule update \
   && git checkout pre_beta \
   && mkdir build \
   && cd build \
   && cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_CUDA=ON \
   && make -j 4

ENV AFQMC_EXEC=/var/app/afqmc/build/bin/safire

# Build Python layer
RUN cd /var/app/ \
   && python3  -m venv venv --system-site-packages \
   && source /var/app/venv/bin/activate \
   && pip install /var/app/afqmc/utils[AUTOHF,PYSCF,TESTING] \
   && cd /var/app/afqmc/utils

# run make test and pytest as entrypoint to verify build
CMD cd /var/app/afqmc/build && ctest --output-on-failure && cd /var/app/afqmc/utils && pytest
