FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# install dependencies
RUN apt-get update && apt-get install -y openssh-client git \
   gcc \
   g++ \
   clang-19 \
   clang-tools-19 \
   cmake \
   libomp-19-dev \
   ninja-build \
   openmpi-bin \
   openmpi-common \
   libopenmpi-dev \
   libopenblas-dev \
   libhdf5-dev \
   python3 \
   python3-pip \
   libboost-dev \
   python3-mpi4py \
   python3-h5py \
   python3-venv \
   catch2 \
   libspdlog1.12 \
   libspdlog-dev

# necessary for building BLIS within TBLIS
ENV CC=/usr/bin/gcc
ENV CXX=/usr/bin/g++
