FROM ubuntu:24.04

ENV DEBIAN_FRONTEND noninteractive

# install dependencies
RUN apt-get update && apt-get install -y openssh-client git \
   gcc \
   g++ \
   cmake \
   openmpi-bin \
   openmpi-common \
   libopenmpi-dev \
   libopenblas-dev \
   libhdf5-openmpi-dev \
   python3 \
   python3-pip \
   libboost-dev \
   python3-mpi4py \
   python3-h5py-mpi \
   python3-venv
