# This file is distributed under the Apache License, Version 2.0 License.
# See LICENSE file in top directory for details.
#
# Copyright (c) 2021-2025 The Simons Foundation, Inc.
#
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "afqmctools"
version = "0.0.3"
requires-python = ">3.9"
dependencies = [
    "numpy > 1.11.2",
    "mpi4py >= 2.0.0",
    "scipy >= 1.11.0",
    "h5py > 2.6.0",
    "pandas",
    "matplotlib",
    "numba",
    "pytest",
    "toml",
    "tables",
]

# domain-specific dependencies are considered optional!
[project.optional-dependencies]
PYSCF = ["pyscf >= 2.4.0"]
AUTOHF = ["jax","optax","jaxlib", "jaxopt"]
LATTICE_HF = ["jax","optax","jaxlib", "jaxopt"] # for backwards compatibility!
TESTING = ["pytest-html","coverage"]
TUTORIALS = ["jupyterlab"]
DOCS = [
    "sphinx",
    "sphinxcontrib-bibtex",
    "sphinx-rtd-theme",
    "nbsphinx",
    "sphinx-autodoc-typehints",
    "numpydoc",
    "myst-nb",
    "jupytext",
    "pydata-sphinx-theme"
]

[tool.setuptools]
packages = [
    "afqmctools",
    "afqmctools.analysis",
    "afqmctools.hamiltonian",
    "afqmctools.hamiltonian.model",
    "afqmctools.inputs",
    "afqmctools.observables",
    "afqmctools.systems",
    "afqmctools.utils",
    "afqmctools.wavefunction",
    "cli",
    "stats",
    "stats.lib",
    "tutorial_utils"
]

[project.scripts]
afqmc_to_fcidump = "cli.afqmc_to_fcidump:main"
dice_to_hdf5 = "cli.dice_to_hdf5:main"
fcidump_to_afqmc = "cli.fcidump_to_afqmc:main"
pyscf_to_afqmc = "cli.pyscf_to_afqmc:main"
test_afqmc_input = "cli.test_afqmc_input:main"
wfn_to_hdf5 = "cli.wfn_to_hdf5:main"
write_afqmc_json = "cli.write_afqmc_json:main"
scalar_stats = "cli.scalar_tab:main"
energy_stats = "cli.scalar_tab:main"
rdm_stats = "cli.observables_stats:main"
make_model_ham = "cli.make_model_ham:main"
fcidump_spat2spin = "cli.fcidump_spat2spin:main"
coqui_to_afqmc = "cli.aimbes_to_afqmc:main"  # TODO: remove once aimbes_to_2nd_quant is well tested
coqui_to_fcidump = "cli.aimbes_to_2nd_quant:main" # TODO: remove once aimbes_to_2nd_quant is well tested
coqui_to_2nd_quant = "cli.aimbes_to_2nd_quant:main"
check_one_rdm = "cli.check_one_rdm:main"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-m 'not functional and not dev and not debug' --verbose --html=./.htmlpytest/pytest.html --strict-markers"
testpaths = [
    "tests",
]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "pyscf: marks tests as pyscf-dependent (deselect with '-m \"not pyscf\"')",
    "aimbes: marks tests as aimbes-dependent",
    "mpi: marks tests that require MPI",
    "past: marks tests that are related to backward-comptability",
    "dev: for tests used as used for test-driven development (TDD)",
    "debug: use only when debugging",
    "weekly: for weekly testing",
    "push: tests to run every push",
    "functional: tests against functional requirements"
]

[tool.coverage.run]
source = [
    "afqmctools/",
    "stats/",
    "AutoHF/"
]
omit = [
    "__init__.py", # no interesting code in __init__.py files right now
]

# configure tools for building documentation

