FUNCTION( ADD_UNIT_TEST TESTNAME TEST_BINARY )
    add_test(NAME ${TESTNAME} COMMAND ${TEST_BINARY} ${ARGN})
ENDFUNCTION()

FUNCTION( ADD_MPI_UNIT_TEST TESTNAME TEST_BINARY PROC_COUNT )
    ADD_TEST(NAME ${TESTNAME} COMMAND ${MPIEXEC_EXECUTABLE} ${MPIEXEC_NUMPROC_FLAG} ${PROC_COUNT} ${MPIEXEC_PREFLAGS} ${TEST_BINARY} ${ARGN})
    SET_TESTS_PROPERTIES( ${TESTNAME} PROPERTIES ENVIRONMENT OMP_NUM_THREADS=1 )
    SET_PROPERTY(TEST ${TESTNAME} APPEND PROPERTY LABELS "mpi")
ENDFUNCTION()

